Repository jotunnlib/jotunnlib, pull requests merged in 2021-03, with the labels that each got.

#11 docs: Added better docs for registering custom input
  JotunnLib/Documentation/tutorials/inputs/overview.md
  TestMod/TestMod.cs
Labels: documentation

#12 chore: Create release on tag with actions
  .github/workflows/tag-release.yml
Labels: devops

#30 fix: Manifest.json dependency
  manifest.json
Labels: bug, critical
